<?php
declare(strict_types=1);

namespace AfroVerified\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260904190000 extends AbstractMigration
{
    public function getDescription(): string { return 'Initial Afroverified public and admin platform schema'; }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(150) NOT NULL, email VARCHAR(190) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(40) NOT NULL DEFAULT 'user', status VARCHAR(30) NOT NULL DEFAULT 'active', phone VARCHAR(40) DEFAULT NULL, location VARCHAR(150) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, last_active_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_USERS_EMAIL (email), INDEX IDX_USERS_ROLE_STATUS (role, status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE organizers (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, name VARCHAR(150) NOT NULL, company VARCHAR(150) DEFAULT NULL, email VARCHAR(190) NOT NULL, phone VARCHAR(40) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, country VARCHAR(100) DEFAULT NULL, instagram VARCHAR(120) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pending', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_ORGANIZER_USER (user_id), INDEX IDX_ORGANIZER_STATUS (status), UNIQUE INDEX UNIQ_ORGANIZER_EMAIL (email), PRIMARY KEY(id), CONSTRAINT FK_ORGANIZER_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE event_categories (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL, description VARCHAR(255) DEFAULT NULL, icon VARCHAR(100) DEFAULT NULL, color VARCHAR(20) DEFAULT NULL, status VARCHAR(30) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_CATEGORY_SLUG (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE venues (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(160) NOT NULL, slug VARCHAR(180) NOT NULL, address VARCHAR(255) NOT NULL, city VARCHAR(100) NOT NULL, region VARCHAR(100) DEFAULT NULL, country VARCHAR(100) NOT NULL, capacity INT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, status VARCHAR(30) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_VENUE_SLUG (slug), INDEX IDX_VENUE_CITY_STATUS (city, status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE events (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, venue_id INT DEFAULT NULL, organizer_id INT NOT NULL, name VARCHAR(190) NOT NULL, slug VARCHAR(210) NOT NULL, subtitle VARCHAR(255) DEFAULT NULL, description LONGTEXT NOT NULL, event_type VARCHAR(80) DEFAULT NULL, subcategory VARCHAR(100) DEFAULT NULL, starts_at DATETIME NOT NULL, ends_at DATETIME DEFAULT NULL, city VARCHAR(100) NOT NULL, country VARCHAR(100) NOT NULL, venue_name VARCHAR(160) DEFAULT NULL, venue_address VARCHAR(255) DEFAULT NULL, poster VARCHAR(255) DEFAULT NULL, hero_image VARCHAR(255) DEFAULT NULL, instagram VARCHAR(120) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, ticket_url VARCHAR(255) DEFAULT NULL, age_restriction VARCHAR(30) DEFAULT NULL, dress_code VARCHAR(120) DEFAULT NULL, status VARCHAR(30) NOT NULL DEFAULT 'draft', featured TINYINT(1) NOT NULL DEFAULT 0, sweet_reckless TINYINT(1) NOT NULL DEFAULT 0, views INT NOT NULL DEFAULT 0, ticket_clicks INT NOT NULL DEFAULT 0, shares INT NOT NULL DEFAULT 0, rating NUMERIC(3, 2) DEFAULT NULL, published_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_EVENT_SLUG (slug), INDEX IDX_EVENT_CATEGORY (category_id), INDEX IDX_EVENT_VENUE (venue_id), INDEX IDX_EVENT_ORGANIZER (organizer_id), INDEX IDX_EVENT_STATUS_DATE (status, starts_at), INDEX IDX_EVENT_FEATURED (featured), PRIMARY KEY(id), CONSTRAINT FK_EVENT_CATEGORY FOREIGN KEY (category_id) REFERENCES event_categories (id), CONSTRAINT FK_EVENT_VENUE FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE SET NULL, CONSTRAINT FK_EVENT_ORGANIZER FOREIGN KEY (organizer_id) REFERENCES organizers (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE event_submissions (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, submitted_by_name VARCHAR(150) NOT NULL, submitted_by_email VARCHAR(190) NOT NULL, submitted_by_phone VARCHAR(40) DEFAULT NULL, payload JSON NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pending', admin_notes LONGTEXT DEFAULT NULL, reviewed_by INT DEFAULT NULL, reviewed_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_SUBMISSION_EVENT (event_id), INDEX IDX_SUBMISSION_REVIEWER (reviewed_by), INDEX IDX_SUBMISSION_STATUS (status), PRIMARY KEY(id), CONSTRAINT FK_SUBMISSION_EVENT FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE SET NULL, CONSTRAINT FK_SUBMISSION_REVIEWER FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE promotions (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, organizer_id INT DEFAULT NULL, name VARCHAR(190) NOT NULL, slug VARCHAR(210) NOT NULL, type VARCHAR(80) NOT NULL, description LONGTEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, starts_at DATETIME NOT NULL, ends_at DATETIME NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'scheduled', impressions INT NOT NULL DEFAULT 0, clicks INT NOT NULL DEFAULT 0, conversions INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_PROMOTION_SLUG (slug), INDEX IDX_PROMOTION_EVENT (event_id), INDEX IDX_PROMOTION_ORGANIZER (organizer_id), PRIMARY KEY(id), CONSTRAINT FK_PROMOTION_EVENT FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE SET NULL, CONSTRAINT FK_PROMOTION_ORGANIZER FOREIGN KEY (organizer_id) REFERENCES organizers (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE vibe_editions (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(190) NOT NULL, slug VARCHAR(210) NOT NULL, city VARCHAR(100) NOT NULL, starts_on DATE NOT NULL, ends_on DATE NOT NULL, banner_image VARCHAR(255) DEFAULT NULL, status VARCHAR(30) NOT NULL DEFAULT 'draft', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_VIBE_SLUG (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE vibe_edition_events (edition_id INT NOT NULL, event_id INT NOT NULL, sort_order INT NOT NULL DEFAULT 0, INDEX IDX_VIBE_ITEM_EDITION (edition_id), INDEX IDX_VIBE_ITEM_EVENT (event_id), PRIMARY KEY(edition_id, event_id), CONSTRAINT FK_VIBE_ITEM_EDITION FOREIGN KEY (edition_id) REFERENCES vibe_editions (id) ON DELETE CASCADE, CONSTRAINT FK_VIBE_ITEM_EVENT FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE message_templates (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(150) NOT NULL, channel VARCHAR(20) NOT NULL, category VARCHAR(80) NOT NULL, subject VARCHAR(255) DEFAULT NULL, html_body LONGTEXT DEFAULT NULL, text_body LONGTEXT NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'active', created_by INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_TEMPLATE_CREATOR (created_by), PRIMARY KEY(id), CONSTRAINT FK_TEMPLATE_CREATOR FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE email_signatures (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(150) NOT NULL, html_body LONGTEXT NOT NULL, text_body LONGTEXT NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'active', created_by INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_SIGNATURE_CREATOR (created_by), PRIMARY KEY(id), CONSTRAINT FK_SIGNATURE_CREATOR FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE notification_definitions (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(150) NOT NULL, category VARCHAR(80) NOT NULL, channels JSON NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE settings (id INT AUTO_INCREMENT NOT NULL, setting_group VARCHAR(80) NOT NULL, setting_key VARCHAR(120) NOT NULL, setting_value JSON NOT NULL, is_public TINYINT(1) NOT NULL DEFAULT 0, updated_by INT DEFAULT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_SETTING_KEY (setting_group, setting_key), INDEX IDX_SETTING_USER (updated_by), PRIMARY KEY(id), CONSTRAINT FK_SETTING_USER FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE newsletter_subscribers (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(190) NOT NULL, source VARCHAR(80) DEFAULT NULL, status VARCHAR(30) NOT NULL DEFAULT 'active', subscribed_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_NEWSLETTER_EMAIL (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE activity_logs (id BIGINT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, action VARCHAR(120) NOT NULL, entity_type VARCHAR(80) DEFAULT NULL, entity_id INT DEFAULT NULL, metadata JSON DEFAULT NULL, ip_address VARCHAR(45) DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_ACTIVITY_USER (user_id), INDEX IDX_ACTIVITY_CREATED (created_at), PRIMARY KEY(id), CONSTRAINT FK_ACTIVITY_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
    }

    public function down(Schema $schema): void
    {
        foreach (['activity_logs','newsletter_subscribers','settings','notification_definitions','email_signatures','message_templates','vibe_edition_events','vibe_editions','promotions','event_submissions','events','venues','event_categories','organizers','users'] as $table) {
            $this->addSql('DROP TABLE IF EXISTS ' . $table);
        }
    }
}
