<?php
declare(strict_types=1);
function av_e($value): string{return htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');}
function av_title($value): string{return ucwords(str_replace(['_','-'],' ',(string)$value));}
function av_date($value,string $format='M j, Y'): string{return $value?date($format,strtotime((string)$value)):'—';}
function av_badge($value): string{$label=av_title($value);$class=preg_match('/Published|Active|Approved/i',$label)?'green':(preg_match('/Pending|Scheduled/i',$label)?'orange':(preg_match('/Rejected|Suspended/i',$label)?'red':(preg_match('/Organizer|Amapiano/i',$label)?'blue':'')));return '<span class="badge '.$class.'">'.av_e($label).'</span>';}
function av_stats(array $items): void{echo '<div class="stats '.(count($items)===5?'five':'').'">';$icons=['▣','●','◷','⊗','▤'];foreach($items as $i=>$item){echo '<div class="stat"><span class="stat-icon">'.$icons[$i%5].'</span><div><strong>'.av_e($item[0]).'</strong><span>'.av_e($item[1]).'</span><div class="trend '.($i===3?'down':'').'">'.($i===3?'↓ 8':'↑ 12').'%<span>vs last month</span></div></div></div>';}echo '</div>';}
function av_head(string $title,string $subtitle,string $button=''): void{echo '<div class="page-head"><div><h1>'.av_e($title).'</h1><p class="subtitle">'.av_e($subtitle).'</p></div>'.($button?'<button class="btn red">'.av_e($button).'</button>':'').'</div>';}
function av_filters(string $placeholder='Search by name, organizer or location...'): void{echo '<div class="filters"><input class="control table-search" placeholder="⌕  '.av_e($placeholder).'"><div class="field"><label>Status</label><select class="control"><option>All Statuses</option><option>Active</option><option>Pending</option></select></div><div class="field"><label>Category</label><select class="control"><option>All Categories</option></select></div><div class="field"><label>Location</label><select class="control"><option>All Locations</option></select></div><button class="btn">Reset</button><button class="btn red">Apply</button></div>';}
function av_pager(int $total,string $label): void{echo '<div class="pagination"><span>Showing 1 to '.min(10,$total).' of '.$total.' '.av_e($label).'</span><div class="pages"><button>‹</button><button class="active">1</button><button>›</button></div></div>';}
$requestPath=parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH)?:'';$nested=strpos($requestPath,'/admin/settings/')!==false;$base=$nested?'../../':'../';$adminBase=$nested?'../':'';
$eventPages=['events','event-details','add-event','categories','venues','submissions'];
$active=in_array($page,$eventPages,true)?'Events':($page==='vibe'?"What's The Vibe":($page==='sweet'?'Sweet & Reckless':($page==='promotions'?'Promotions':($page==='organizers'?'Organizers':($page==='users'?'Users':($page==='reports'?'Reports':(in_array($page,['communication','email','sms','templates','signatures','notifications'],true)?'Settings':'Dashboard')))))));
$nav=['Dashboard'=>['⌂','dashboard.html'],'Events'=>['▣','events.html'],"What's The Vibe"=>['♧','whats-the-vibe.html'],'Sweet & Reckless'=>['♫','sweet-and-reckless.html'],'Promotions'=>['⚑','promotions.html'],'Organizers'=>['▧','organizers.html'],'Users'=>['♟','users.html'],'Reports'=>['▤','reports.html'],'Settings'=>['⚙','settings/communication.html']];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=av_e(av_title($page))?> | Afroverified Admin</title><style>html,body{margin:0;background:#050708}</style><link rel="stylesheet" href="<?=$adminBase?>admin.css?v=20260905.2"></head><body class="admin-ready" data-page="<?=av_e($page)?>"><div class="shell"><aside class="sidebar"><img class="logo" src="<?=$base?>assets/images/logo-dark.png" alt="Afroverified"><nav class="nav"><?php foreach($nav as $label=>$item):?><a class="<?=$active===$label?'active':''?>" href="<?=$adminBase.av_e($item[1])?>"><span class="ico"><?=av_e($item[0])?></span><?=av_e($label)?></a><?php if($label==='Events'&&in_array($page,$eventPages,true)):?><div class="subnav"><?php foreach([['events.html','All Events','events'],['add-event.html','Add New Event','add-event'],['event-categories.html','Categories','categories'],['event-venues.html','Venues','venues'],['event-submissions.html','Event Submissions','submissions']] as $sub):?><a class="<?=$page===$sub[2]?'active':''?>" href="<?=$adminBase.$sub[0]?>"><?=av_e($sub[1])?></a><?php endforeach?></div><?php endif?><?php endforeach?></nav><div class="sidebar-bottom"><a class="back" href="<?=$base?>index.html">← &nbsp; Back to Website</a><div class="profile"><span class="avatar"><?=av_e(strtoupper(substr($user['name'],0,1)).strtoupper(substr(strrchr($user['name'],' ')?:$user['name'],1,1)))?></span><span class="profile-meta"><?=av_e($user['name'])?><small><?=av_e(av_title($user['role']))?></small></span></div></div></aside><div class="mobile-overlay"></div><header class="topbar"><button class="hamb" aria-label="Open menu">☰</button><input class="search" placeholder="⌕ Search events, organizers, users..."><div class="top-right"><span>♧<b style="color:red">•</b></span><span class="avatar"><?=av_e(strtoupper(substr($user['name'],0,1)))?></span><span class="profile-meta"><?=av_e($user['name'])?><small><?=av_e(av_title($user['role']))?></small></span></div></header><div class="content"><?php require __DIR__.'/content.php';?><footer class="footer">© <?=date('Y')?> Afroverified. All rights reserved.<span style="float:right">Privacy Policy　 Terms of Service　 Help & Support</span></footer></div></div><div class="modal"><div class="modal-box"><h2>Confirm action</h2><p>This action cannot be undone.</p><button class="btn modal-cancel">Cancel</button> <button class="btn red modal-confirm">Confirm</button></div></div><script src="<?=$adminBase?>admin-monolith.js?v=20260905.2"></script><script src="<?=$adminBase?>admin-api.js?v=20260905.2"></script></body></html>
